blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/nfx-libs/nfx-hashing/discussions
    about: Ask questions and discuss ideas with the community
  - name: ðŸ“š Documentation
    url: https://nfx-libs.github.io/nfx-hashing/
    about: Browse the full documentation
